### ISSUE TITLE
Independent Transitions

### ISSUE THREAD

**Issue by grahammendick** [tannerlinsley/react-move#13]
There’s a [brilliant feature](https://github.com/tannerlinsley/react-move/blob/269c80a151e9cf6edadf617b4d287c93a623eef8/src/Animate.js#L68) that `Animate` has but `Transition` doesn’t. You can have independent animations by setting `immutable` to false.

You can see what I mean with this [codepen example](https://codepen.io/anon/pen/ZKoddw?editors=0010). It has two `Animate` components both with a duration of 4 seconds. The first `Animate` component appears immediately but the second one only appears after 2 seconds. When the second one appears, the first one doesn’t change its stride. It keeps going at the same pace and reaches its target after 4 seconds. The second one gets to the same point after a further 2 seconds.

Have a look at this [same example](https://codepen.io/anon/pen/LymwEG?editors=0010) but using `Transition` instead of `Animate`. As soon as the second component appears, the first one slows down and they both reach the target at the same time. They aren’t behaving independently like they do in the `Animate` example. This example behaves like the `Animate` one does if you set `immutable` to true.

What do you think about changing `Transition` so that the animations can run independently like they can with `Animate` by setting immutable to false? 

To really have independent animations, the durations also have to be independent. This already works with `Animate` which you can see in this [codepen example](https://codepen.io/anon/pen/oWdKxL?editors=0010). It has two `Animate` components. The first has a duration of 4 seconds and the second appears after 2 seconds and has a duration of 8 seconds. When the second component appears, the first one keeps going at the same pace.

This doesn’t work for the equivalent `Transition` [codepen example](https://codepen.io/anon/pen/dWexMp?editors=0010). As soon as the second item appears, the first slows down and they both complete at the same time.

What do you think about changing `Transition` so that the duration (and easing) lives with the item?

**Comment by tannerlinsley** [comment]
That seems more like react-motion's API and you are right, Items should act independently from one another. The changes would be or tremendous, but If you would like to sketch it out, I would be happy to work on it with you.

**Comment by tannerlinsley** [comment]
Technically speaking, I believe that an items progress should only reset when it's destination data changes via update. Does that sound right?

**Comment by grahammendick** [comment]
Yes, that sounds spot on! It would be nice if an item's duration and easing only reset on data changes. too.

**Comment by tannerlinsley** [comment]
Yeah. Basically if the items destination changes, reset and recalibrate
everything pertaining to that item

**Comment by grahammendick** [comment]
Yep, that ticks all the boxes 👍

**Comment by tannerlinsley** [comment]
Okay. 👌 do you feel comfortable drafting those changes? I will be pretty
straight forward until staggering. Even I get stuck there pretty easily.

**Comment by grahammendick** [comment]
I’ve got my own [navigation project](http://grahammendick.github.io/navigation/index.html) that kinda takes up all my time - thanks for asking though. I’m in the process of swapping out React Motion for React Move in the React Native plugin.

**Comment by tannerlinsley** [comment]
Okay. I will get to it when I have some free time. Currently working a lot of react-table and react-charts.

**Comment by tannerlinsley** [comment]
Implemented in #16

**Comment by tannerlinsley** [comment]
This turned out to be a bit of a challenge, but I figured it out.  Each item now maintains its own progress and invalidation. So now, if you interrupt a Transition with new updates, only items that need to change their destination will update, leaving any remaining items to finish their previous transition with their original timing.

**Comment by grahammendick** [comment]
Thanks but I think it’s only halfway there. It fixed the first of my codepen examples but it’s broken the second one. Have a look at the [weird behaviour of the second example](https://codepen.io/anon/pen/dWexMp?editors=0010) to see what I mean

**Comment by tannerlinsley** [comment]
I'll look into it

**Comment by tannerlinsley** [comment]
@grahammendick Its now fixed :) https://codepen.io/anon/pen/dWexMp?editors=0110

**Comment by grahammendick** [comment]
Great work! Don't you need to do the same for the easing?

**Comment by tannerlinsley** [comment]
…. yeah haha.

**Comment by tannerlinsley** [comment]
Fixed.  Along with some cool enhancements.  You'll probably want to look at the newly created props `getDuration` and `getEasing` ;)

**Comment by grahammendick** [comment]
Very classy! Thanks for doing such a great job.
I'll get back in touch when I release [Navigation with React Move.](http://grahammendick.github.io/navigation/index.html)

**Comment by tannerlinsley** [comment]
What is the primary difference between your Navigation component and React
Router v4?

**Comment by grahammendick** [comment]
Navigation is the data-first router. You concentrate on what data you want to pass and don’t worry about your routes until the end. Take a look at this [counter example](https://codepen.io/anon/pen/oWVOrd?editors=0010). There’s no URLs in sight, right? Just typed data - **the count is passed as a number, not a string**.

Once your app’s up and running you can change the URLs to be whatever you want without changing any code. In the counter example, you can change the count parameter from the query string to the route without touching the component (just set the route on line 18 to `route: '{count?}'`).

The Navigation router gets out of your way. It doesn’t get involved in rendering. It’s almost the exact opposite of the React Router. The React Router is really just a rendering pattern and it provides almost no help with data-passing.

**Comment by grahammendick** [comment]
Any reason you're not calling `onRest` in `Transition` component anymore? I was relying on it being called 😞

**Comment by tannerlinsley** [comment]
My bad. I'll add it back in on both components

**Comment by tannerlinsley** [comment]
@grahammendick It's back now. Available for both `Animate` and `Transition` and finally documented :)  `Animate.onRest` is simply a callback, but `Transition.onRest` will give you the item and its key that came to rest.

**Comment by grahammendick** [comment]
Hmmm....`onRest` in `Transition` component is incorrectly called all the time now. It used to be behind a `wasAnimating` check so that it was only called when it really came to rest.

I think each item should have a `wasAnimating` flag on it, much like each one now has a `duration` and `easing`?

**Comment by tannerlinsley** [comment]
Yeah

**Comment by grahammendick** [comment]
Hey @tannerlinsley, just checking this `onRest` issue is still on your radar

**Comment by tannerlinsley** [comment]
Its released! Check the documentation.

**Comment by grahammendick** [comment]
Sorry, been away for a while. I've added an [`onRest` with a `console.log` to the second example](https://codepen.io/anon/pen/jwqExR?editors=0011). It should only log twice, but it logs v many times instead.
