### ISSUE TITLE
Install from NPM

### ISSUE THREAD

**Issue by thomasbritton** [tannerlinsley/react-move#3]
## Problem Description
You only list yarn as the only place to install from when it's available on npm: https://www.npmjs.com/package/react-move

**Comment by tannerlinsley** [comment]
I've added it to the readme :) Thanks!

**Comment by wilomgfx** [comment]
@thomasbritton of course its available on NPM :p. Where do you think yarn pulls packages ;)

**Comment by derekperkins** [comment]
I think that's obvious to yarn users, but to someone using npm that may have only heard about yarn, it's not obvious.
