### ISSUE TITLE
No Typescript type definitions

### ISSUE THREAD

**Issue by richthornton** [tannerlinsley/react-move#5]
## Problem Description
Currently there aren't any Typescript type definitions for this library.

**Comment by richthornton** [comment]
I should add: Is this something you'd be open to adding to your library? I would be more than happy to open a PR and add the type definitions if it's something you're open to.

**Comment by tannerlinsley** [comment]
Sure!  Keep in mind, I’m optimizing the library right now and adding some
features here and there. As long as you’re good with that, go for it!

**Comment by richthornton** [comment]
Sounds great! I'll open a PR for it tomorrow.

**Comment by tannerlinsley** [comment]
Any progress on this?

**Comment by richthornton** [comment]
Sorry for the delay on this 😟, I've just opened a PR for it

**Comment by tannerlinsley** [comment]
Now available in version 1.1.6
