### ISSUE TITLE
Animate page transitions or unmounted to mounted component

### ISSUE THREAD

**Issue by codepunkt** [tannerlinsley/react-move#6]
Is it possible to animate page transitions or, generally speaking, unmounted to mounted component?

Would be great to have examples!

**Comment by tannerlinsley** [comment]
Yes you can! I'll cook some up asap.

**Comment by tannerlinsley** [comment]
This might help.  Its untested, but it *should* work, possibly with some tweaking, but it's 99% of the way there I think.

Using React-Move with React-Router:
https://gist.github.com/tannerlinsley/b8bf1e54515a11e5758ec36c8e4c5b59

**Comment by tannerlinsley** [comment]
As for animating a single component from unmounted => mounted => unmounted, you must approach it the same way react-motion does by using `<Transition />`. You first feed it an empty data list. Then you add a single item to the list (which represents the component you wish to render), and then when you wish to animate an unmount, you must remove that item from the list.  This should accomplish all of the view state you want. :) I'll try and work up an example for the docs, but closing this issue for now.

**Comment by 0py** [comment]
@tannerlinsley @codepunkt Hi! I tried the Gist and the initial render of the route is animated, but not when switching routes. Can you please provide a complete example? @codepunkt Did you get this to work?

**Comment by cusxio** [comment]
> I'll try and work up an example for the docs, but closing this issue for now.

@tannerlinsley 

would love to see an example for this!
