### ISSUE TITLE
Doesn’t Work on React Native

### ISSUE THREAD

**Issue by grahammendick** [tannerlinsley/react-move#7]
Thanks for React Move. It’s exactly what I’ve been looking for. Looks like it will fix all the problems I was having with React Motion. The only problem is it doesn’t work with React Native yet. Here are the two problems that are standing in its way, along with suggested fixes.

## Transform Error 
You can’t start up a React Native project that imports React Move because you get a Transform Error that says “couldn't find preset es2015”. 
### Solution
Removing the babel section from `package.json`, https://github.com/tannerlinsley/react-move/blob/master/package.json#L89, lets you start up the React Native project successfully

## Transition Doesn’t Move
After applying the fix above, the project starts but Transition doesn’t actually move. The `progress` goes from 0 to 1 in just one step and so components don’t animate
### Solution
Removing the `timestamp` from the current time calculation, https://github.com/tannerlinsley/react-move/blob/master/src/Transition.js#L220, changes it to `let currentTime = now()` and this gets the transition moving. (This matches the similar code from the Animate component, https://github.com/tannerlinsley/react-move/blob/master/src/Animate.js#L134)

**Comment by tannerlinsley** [comment]
These should be simple to fix. I'll make a release tomorrow :)

**Comment by tannerlinsley** [comment]
Fixed in https://github.com/tannerlinsley/react-move/releases/tag/v1.1.5 :)
